### ISSUE TITLE
如何打开电脑内置的欧陆词典

### ISSUE THREAD

**Issue by akiraruan** [tisfeng/Raycast-Easydict#16]
请问一下怎么打开电脑内置的欧陆词典，我看readme上是支持的，但是没发现在哪里打开

**Comment by tisfeng** [comment]
@akiraruan 如果你电脑上安装了欧路词典，查询单词后在右下角会自动显示一个 `Open In Eudic` 按钮。

![](https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/easydict-1-1658309667-1658309686.png)

**Comment by akiraruan** [comment]
谢谢回复，但是我电脑上没出现这个按钮，截图如下，多次重装插件和欧陆都没能解决问题。我用的是欧陆普通版，是仅支持高级版吗，还是我欧陆的设置哪里出了问题。
<img width="1879" alt="image" src="https://user-images.githubusercontent.com/23556908/182010882-c8de80f0-e3ec-4c2a-bb9b-8366e4043451.png">

**Comment by tisfeng** [comment]
不，目前仅支持普通版，我没用高级版测过。这看起来像个 bug，你复制看一下欧路词典的 buildle id 是什么？

<img width="1000" alt="Raycast 2022-07-31 at 13 10 00" src="https://user-images.githubusercontent.com/25194972/182011111-72a747bd-2064-4b55-bed4-b0bca28ad0aa.png">

**Comment by akiraruan** [comment]
com.eusoft.eudic，我是从官网上下载的http://www.eudic.net/v4/en/app/download

**Comment by tisfeng** [comment]
Ok，破案了，因为欧路词典有多个版本，免费版和高级版，其中又分 App Store 商店版和官网版本，它们的 buildle id 不相同导致😓  

稍后我会更新一个版本修复这个问题。

当前代码是写死的 `com.eusoft.freeeudic`（App Store 免费版），你可以把它改成你的 buildle id 试试。

```ts
export const eudicBundleId = "com.eusoft.freeeudic";
```

**Comment by akiraruan** [comment]
好的，谢谢作者

**Comment by tisfeng** [comment]
已向商店提交更新 PR https://github.com/raycast/extensions/pull/2445
