### ISSUE TITLE
优化启动速度

### ISSUE THREAD

**Issue by sihaixianyu** [tisfeng/Raycast-Easydict#17]
每次打开的时候需要等待一定时间才能输入并显示，能不能优化一下启动速度（或者typing立刻显示，查询结果允许延迟）。

**Comment by tisfeng** [comment]
我研究一下👌

**Comment by tisfeng** [comment]
问题已定位，稍后发版修复。

**Comment by sihaixianyu** [comment]
优秀，给大佬点赞，哈哈。

**Comment by tisfeng** [comment]
该问题已修复 https://github.com/tisfeng/Raycast-Easydict/releases/tag/2.3.0 ，商店版也已提交 PR。
