### ISSUE TITLE
新版本 youdao 报错，已经填写了密钥

### ISSUE THREAD

**Issue by Jax0rz** [tisfeng/Raycast-Easydict#18]
版本号2.3.0

**Comment by tisfeng** [comment]
你好，请问具体报错信息是什么，贴一下错误日志？

**Comment by Jax0rz** [comment]
> 你好，请问具体报错信息是什么，贴一下错误日志？

<img width="862" alt="CleanShot 2022-09-23 at 23 17 16@2x" src="https://user-images.githubusercontent.com/7557357/191995081-721143de-2a7b-41c4-ab20-ac451b6e1907.png">

**Comment by tisfeng** [comment]
这个报错，是有道接口无法认证你的证书，看起来像是你开启了 `Use System Proxy`，并且使用了抓包工具 MITM 导致？

**Comment by Jax0rz** [comment]
> 这个报错，是有道接口无法认证你的证书，看起来像是你开启了 `Use System Proxy`，并且使用了抓包工具 MITM 导致？

对，我在用surge，MITM开启了

**Comment by tisfeng** [comment]
那就没问题，因为有道的接口会对请求证书做校验，而 `Easydict` 支持系统代理，如果又启用了系统代理就会导致这样。

一般情况不建议开启 `Use System Proxy`，除了使响应变慢外，还可能导致一些其他异常情况，如证书校验等问题（虽然我已尽力处理了一些场景。。）

**Comment by tisfeng** [comment]
> 对，我在用surge，MITM开启了；很奇怪今天这个新版本之前都是正常的。

这其实是之前的一个小问题：开启系统代理需要一点时间（大约 0.5s），某些请求可能在开启代理之前就已经发出去了，所以才没有导致问题。

但我在 `v2.3.0` 版本修复了这个问题，目前如果打开了系统代理开关，那么所有请求都会等待系统代理开启后才发送。
