### ISSUE TITLE
【功能建议】允许将 Easydict 作为 Fallback Command

### ISSUE THREAD

**Issue by nb5p** [tisfeng/Raycast-Easydict#23]
## 功能描述

希望可以将 Easydict 作为 [fallback command](https://manual.raycast.com/fallback-commands) 。
抱歉，我不太了解 Raycast 是否对第三方扩展开放此功能。如果可行的话，希望能够添加。

**Comment by tisfeng** [comment]
好想法，但目前来看似乎不可能，现在只支持 Quicklinks 和  Script Commands 作为 `Fallback Commands` 
 

https://github.com/raycast/extensions/issues/1668#issuecomment-1167059165

> The available section now contains all your [Quicklinks](https://github.com/8cc9c64a077a440189858c074492e8d8) and [Script Commands](https://github.com/771ff9351bc54ee88fa9c585b7782e22) with single argument. You can just hit enter on any of that to enable.

等后面开放 API 吧。

**Comment by tisfeng** [comment]
最新 1.45.0 版本，已允许使用开发者的 Commands 作为 `Fallback Commands`   

https://developers.raycast.com/changelog#1.45.0-2022-12-14
