### ISSUE TITLE
回车键复制翻译结果

### ISSUE THREAD

**Issue by unicorn1009** [tisfeng/Raycast-Easydict#24]
## 功能描述
翻译完成后，回车默认会打开对应翻译产品的官网。如果需要拷贝翻译结果，需要先按cmd+k再回车，请问是否可以更改为回车即复制结果呢？

**Comment by tisfeng** [comment]
收到，我尝试一下看看效果。

能否看一下你 `Cmd + K` 的界面截图？

**Comment by unicorn1009** [comment]
> 
如图，如果需要拷贝翻译结果，需要cmd+k再回车。是否可以增加一个配置项，设置为选择翻译结果直接回车即拷贝到粘贴板呢
<img width="762" alt="image" src="https://user-images.githubusercontent.com/39911458/194806293-860e6f70-e108-44eb-b5d9-df60f0b57068.png">

**Comment by unicorn1009** [comment]
> 收到，我尝试一下看看效果。
> 
> 能否看一下你 `Cmd + K` 的界面截图？

如图，如果需要拷贝翻译结果，需要cmd+k再回车。是否可以增加一个配置项，设置为选择翻译结果直接回车即拷贝到粘贴板呢
<img width="762" alt="image" src="https://user-images.githubusercontent.com/39911458/194807187-b1d4f357-4a56-4302-901b-5a23f8382337.png">

**Comment by tisfeng** [comment]
我明白你的意思了。 这里面比较复杂，我简单说一下。

其实目前我并没有给拷贝结果和打开官网设置快捷键，这个 `return` 和 `cmd + return` 是 Raycast 默认的快捷键，Raycast 会自动给最前的 2 个动作添加快捷键。

但这里的问题是，谁是最前两个动作不确定，当前默认设置的置顶动作是 `Open In Eudic App`，如图所示，但这个动作仅在用户电脑上安装了 [Eudic](https://apps.apple.com/us/app/eudic-%E6%AC%A7%E8%B7%AF%E8%AF%8D%E5%85%B8/id434350458?l=zh&mt=12) 且在设置中开启了才会显示。 

第二个默认的动作才是打开对应服务的官网，但并不是所有的服务都会有这个选项，如腾讯翻译就没有，因为它没有查询的直达链接。另外由于要同时显示多个打开官网的动作，假如要设置快捷键的话，就得分别设置多个，这样又会占用过多的快捷键资源 😓

综上，为了使用方便，也为了节省快捷键，所以上面两个动作我都没有专门设置快捷键，而是借用了 Raycast 默认快捷键。

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/194833881-429c7380-3e8b-463d-87ee-ef2ed4727b3f.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/194835264-3d477ab1-d6cd-457b-9e70-460ebeee20b6.png">

**Comment by tisfeng** [comment]
目前，拷贝结果动作还没有设置专门的快捷键，稍后我会为它添加一个 `Cmd + Y` 的快捷键，这算是一种折中方案吧。

当然，如果你能提供更好的解决方案，我会很乐意采纳的 😄

**Comment by unicorn1009** [comment]
> 目前，拷贝结果动作还没有设置专门的快捷键，稍后我会为它添加一个 `Cmd + Y` 的快捷键，这算是一种折中方案吧。
> 
> 当然，如果你能提供更好的解决方案，我会很乐意采纳的 😄
能否像下图这样，翻译后，return即copy，在cmd+K菜单中，return为第一顺位。因为平时最常用的操作就是翻译-复制、翻译-复制。。。
<img width="762" alt="image" src="https://user-images.githubusercontent.com/39911458/194858417-02d378b9-550f-46f9-bb87-c897fe9ed815.png">

**Comment by tisfeng** [comment]
> 能否像下图这样，翻译后，return即copy，在cmd+K菜单中，return为第一顺位。因为平时最常用的操作就是翻译-复制、翻译-复制。。。


感谢你的反馈，我考虑一下。

**Comment by tisfeng** [comment]
增加了 `Show Copy Text First` 选项，默认开启。该功能会在下一个版本发布。

感谢你的建议～

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/194891370-1a0f51ec-c351-4a96-8510-35b2863301ad.png">

**Comment by tisfeng** [comment]
@unicorn1009 你好👋，最新版我已改用 `return` 复制文本了，你可以手动安装试一下效果。

### 手动安装
```
git clone https://github.com/tisfeng/Raycast-Easydict.git && cd Raycast-Easydict

npm install && npm run dev
```

**Comment by unicorn1009** [comment]
> @unicorn1009 你好👋，最新版我已改用 `return` 复制文本了，你可以手动安装试一下效果。
> 
> ### 手动安装
> ```
> git clone https://github.com/tisfeng/Raycast-Easydict.git && cd Raycast-Easydict
> 
> npm install && npm run dev
> ```

没有变化呀，是main分支吗？是不是你忘了推到远程分支了？

**Comment by tisfeng** [comment]
对应代码 https://github.com/tisfeng/Raycast-Easydict/commit/9514695b6477571c0829b8dd24a0e4139470dced

你看一下你有正确运行上面的代码吗？看一下你 `Easydict` 的偏好设置页面以及 `Cmd + K` 页面截图

**Comment by unicorn1009** [comment]
> 对应代码 [9514695](https://github.com/tisfeng/Raycast-Easydict/commit/9514695b6477571c0829b8dd24a0e4139470dced)
> 
> 你看一下你有正确运行上面的代码吗？看一下你 `Easydict` 的偏好设置页面以及 `Cmd + K` 页面截图

有了，我刚看错了，打开的是之前从商店安装的，npm安装的是和商店安装的同时存在，现在没问题了，我可以把商店的版本卸载了，兄弟辛苦了🌹
<img width="760" alt="image" src="https://user-images.githubusercontent.com/39911458/195011189-6a5ad5d5-90fb-40b2-916c-d27e42dc2fa7.png">
<img width="762" alt="image" src="https://user-images.githubusercontent.com/39911458/195011286-3a70389d-a140-4c04-89c8-9e668cba0523.png">

**Comment by tisfeng** [comment]
商店版功能更新已发布。
