### ISSUE TITLE
关于快捷键的问题。

### ISSUE THREAD

**Issue by lesserror-hxr** [tisfeng/Raycast-Easydict#25]
## 功能描述

翻译是一个很高频的操作，我之前用的一个工具，可以双击 command键实现聚合翻译，这样既不容易误触也很容易快捷操作。

但是在 raycast 中的组合键又很容易和其他应用的快捷键冲突，设置太复杂了，又不方便触发翻译？ 有什么好的办法吗？

**Comment by tisfeng** [comment]
额，理论上最快捷的触发方式就是快捷键了。如果翻译功能对你来说是一个很高频的操作，那它应该值得你为它设置一个独一无二的快捷键，而且因为 Raycast 是支持手动设置快捷键的，所以理论上也不会和其他应用的快捷键发生冲突。

Raycast 的[快捷键格式](https://developers.raycast.com/api-reference/keyboard)至少是一个修饰键 + 一个普通按键，所以不能设置为双击 Cmd。

> 设置太复杂了

另外，我很好奇，你说的设置太复杂了，具体是指什么？ Raycast 快捷键的功能， 可以很方便为每个扩展设置单独的快捷键，这功能我觉得很好用啊 🧐

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/25194972/197539053-70e12b17-c5c8-4fed-922e-4d48353b430a.png">

**Comment by lesserror-hxr** [comment]
嗯，谢谢回答。 

我想表达的是修饰键 + 一个普通键，真的很容易和其他应用的冲突，为什么这么说呢？ 因为我翻译的动作是高频的，所以这个快捷键一定要非常容易按到，并且很“傻瓜式”的。这样一来，肯定是容易单手触发+离手指近的快捷键。

例如你这里的 cmd + E 他是和 obsidian 中的 预览和编辑视图切换冲突了。 在 vscode 中也冲突了。

我目前改的是 option + E 。勉强着用吧。 我之前有 一款 叫 「utools」的工具是双击cmd键聚合翻译的。 这个希望你能 get 到我的痛点。这个目前来看没有好的解决方案，因为 raycast 不能双击修饰键。

-------------------------------------------

还有一点是，复制长句翻译的时候，raycast 的输入框中，复制的英文全文就显示不全了，这个还挺不方便的。有时需要对照英文全文根据自己的理解来翻译。 例如另外一款翻译聚合翻译工具的界面是这样的，其实我更喜欢 Easydict 的形式。只要输入框能显示全所有的英文就很完美了。

例如 Easydict 在翻译英语长文时的 输入框的样子：
<img width="759" alt="image" src="https://user-images.githubusercontent.com/33254127/197672751-2a33097c-4255-47ab-9b2b-3b206bf3c8d9.png">

另外一款工具的样子：

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/33254127/197672971-0633633f-c357-4247-9681-ca8a4a8d3f36.png">


bob 的翻译 在选择的文字下面弹出一个翻译框，我感觉也行？ 没实际用过bob。

**Comment by tisfeng** [comment]
好的，我理解你的想法了 😌

快捷键方面，目前只能这样了。如果是担心和浏览器的快捷键冲突，可以尝试一个这个插件 [shortkeys-custom-keyboard](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck)，它可以修改或重置 Chrome 的快捷键。

如果你使用 `PopClip` 的话，可以参考这里  [Use with PopClip](https://github.com/tisfeng/Raycast-Easydict#use-with-popclip) 曲线救国救一下，给它设置一个较复杂的触发快捷而又不用担心冲突。

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/25194972/197676123-302a9b8d-be58-4a82-bad9-ff753d7e6139.png">

**Comment by tisfeng** [comment]
> 复制的英文全文就显示不全了

这个也不是 `Easydict` 的问题 😅，Raycast 的设定就是这样，输入框只能显示这么多内容，目前很多 UI 样式都还未开放，所以作为扩展也无法自定义修改。

不过，你可以通过动作 `Show More Details` 查看完整详情页面。

<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/197677430-7c19d32a-385c-4293-bc71-9198c56df7cb.png">

**Comment by tisfeng** [comment]
其实，`Easydict` 作为一个扩展程序，很多功能方面难免都会受到 Raycast 的制约和限制，所以后续我可能会开发一个桌面版 App，这样就能足够自由，大展身手。

**Comment by lesserror-hxr** [comment]
感谢回答，目前先尝试用 PopClip 曲线救国，哈哈哈。

**Comment by tisfeng** [comment]
@lesserror-hxr 好消息，Raycast 刚刚支持了新的快捷键，可以 cmd + cmd 了 🎉🎉

<img width="1000" alt="Raycast 2022-10-26 at 21 23 58" src="https://user-images.githubusercontent.com/25194972/198038056-1d68b064-b7a1-4e52-a044-a0b40e84238c.png">
