### ISSUE TITLE
复制翻译的内容的时候，会多复制一个换行符，你可以试一下。

### ISSUE THREAD

**Issue by lesserror-hxr** [tisfeng/Raycast-Easydict#26]
问题如图。

<img width="783" alt="image" src="https://user-images.githubusercontent.com/33254127/199986691-133227da-8989-47ff-a4f3-89088e1cf050.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/33254127/199986721-669d3663-5a71-4b5b-80b8-15935af85661.png">

**Comment by tisfeng** [comment]
好的，感谢反馈，我稍后看一下。

**Comment by tisfeng** [comment]
你好，你说的复制，是指回车 `Copy Text` 吗？

**Comment by tisfeng** [comment]
这个问题我无法复现，麻烦提供一下详细信息。

**Comment by lesserror-hxr** [comment]
嗯，就是 cmd + m，展示翻译详细信息。然后 cmd + c 复制翻译内容呀。

**Comment by tisfeng** [comment]
我调试打印看了一下，我这边并没有多一个换行符。。你 `Copy Text` 回车动作复制试一下看，另外，你用别的文本编辑器粘贴看看结果，比如 VScode。

你用的是什么编辑器，我怀疑是你这个编辑器粘贴时会有额外动作。

**Comment by tisfeng** [comment]
没有问题，我就先关闭 issue 了。
