### ISSUE TITLE
[Easy Dictionary] 使用百度输入法输入中文的时候会变成英文字符而不是中文

### ISSUE THREAD

**Issue by TankNee** [tisfeng/Raycast-Easydict#27]
# Extension – [Easy Dictionary](https://github.com/raycast/extensions/tree/8fe95a3ccfadcd7860a44f016e609f1e6e0deeea/extensions/easydict/)
Author: @tisfeng

## Description

<img width="769" alt="image" src="https://user-images.githubusercontent.com/43956168/202878944-4eceb54d-e696-419c-94b8-bcfd6b88a2c4.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/43956168/202878948-2027c788-76ba-4c0a-a859-e4f69e185454.png">

## Steps To Reproduce

1. 安装百度输入法
2. 打开 Easy Dictionary
3. 第一次输入一串中文
4. 在插件查询翻译的过程中输入中文
5. 之后就会出现英文字符以及间隔符

## The current behavior

如截图所示

## The expected behavior

应该输入的还是中文，而不是英文字符

### Raycast version

1.43.2

### 插件版本

最新版

**Comment by tisfeng** [comment]
你好，感谢你的反馈，该问题是最近的 Raycast API bug 导致，我已向官方提了 issue，相信很快会修复的。

当前可以使用划词搜索，或 Arguments 参数方式来查询中文内容。
<img width="810" alt="image" src="https://user-images.githubusercontent.com/25194972/202881228-f21d4826-f4dc-47d3-a412-4ccb080e5f23.png">

**Comment by TankNee** [comment]
Thanks.

**Comment by TankNee** [comment]
最新的1.44.0也没有修复这个问题

**Comment by tisfeng** [comment]
好像是的，我提的 issue 都还没受理 😓

**Comment by tisfeng** [comment]
最新 1.45.0 该问题已修复 https://github.com/raycast/extensions/issues/3496#issuecomment-1353230708
