### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by mbeoliero** [tisfeng/Raycast-Easydict#28]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/24428238/206421035-fcc9f5aa-46c5-43ac-967f-544bec994d25.png">
第一次输完你按空格后，后续的输入再按空格会变成拼音

**Comment by tisfeng** [comment]
感谢反馈，这应该和置顶 issue https://github.com/tisfeng/Raycast-Easydict/issues/27 一样，是 Raycast API 的 Bug，我已经报给官方了，他们说下个版本会修复。

**Comment by mbeoliero** [comment]
> <img alt="image" width="750" src="https://user-images.githubusercontent.com/24428238/206421035-fcc9f5aa-46c5-43ac-967f-544bec994d25.png">
> 
> 第一次输完你按空格后，后续的输入再按空格会变成拼音

**Comment by mbeoliero** [comment]
> 感谢反馈，这应该和置顶 issue #27 一样，是 Raycast API 的 Bug，我已经报给官方了，他们说下个版本会修复。

ok 感谢
