### ISSUE TITLE
使用的人没发现很卡顿吗，每次刚进去就会卡住

### ISSUE THREAD

**Issue by eddievim** [tisfeng/Raycast-Easydict#29]
## 描述问题
进入内容搜索页面，都会卡顿1～3秒

## 复现步骤
1. 随意复现
2. 修改配置也没用

## 期望的结果
1. 进入easy-dict搜索页面应该是流畅的

## 运行环境

- Device: 
- macOS:

**Comment by tisfeng** [comment]
额，还真没有。。Easydict 有快捷键触发，参数触发和手动输入查询三种启动模式，在我的设计和测试中，它们的启动响应时间应该都在 100ms 以内，通常不会有感知的。

当然，这只是我个人的大量测试，毕竟这个扩展目前的用户比较少，很多复杂极端的网络及设备环境可能并没有测试到。

你可以提供一下详细的复现流程吗？最好能录个视频。

**Comment by l782993610** [comment]
我觉得很快啊，比沙拉查词都快很多，是我用过最快的插件，你是不是有什么网络设置问题。

**Comment by Apolsus** [comment]
现在直接使用快捷键触发，翻译速度非常快。但是如果从 raycast 界面进入并慢慢打字搜索，就会慢。这可能是什么原因导致的？

**Comment by tisfeng** [comment]
请问触发方式是 `fallback command` 还是 `arguments` ？按理说速度应该差不多，可以录个视频看一下吗

**Comment by Apolsus** [comment]
今天用又没有问题了，下次出现我再看看吧

**Comment by Apolsus** [comment]
出现了，参数方式等了 15 s。使用快捷键的方法就秒出了。![CleanShot 2023-03-23 at 15 25 24](https://user-images.githubusercontent.com/59809602/227132796-4a4d2d3d-8926-453d-bce9-8dbc619a15ed.gif)

**Comment by tisfeng** [comment]
看视频显示，输入查询后有  loading 动画在进行，说明程序在正常运行，这应该是语种识别过程卡住了 😢 

在线语种识别 API 偶尔不太稳定，再加上我代码判断写得太严格了，可能会遇到这种问题 。稍后我优化一下，放宽识别判定。

**Comment by tisfeng** [comment]
你这个设置选项是开启的吗？默认是开启的，这样语种识别会快一些。

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/25194972/227168036-1a53784e-a1e6-431e-8bc3-c4fb7cec8657.png">

**Comment by Apolsus** [comment]
是的。
<img width="304" alt="image" src="https://user-images.githubusercontent.com/59809602/227448223-49beb6f6-cf31-4596-a3bf-6a00768baaba.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/59809602/227448357-7c5773ad-56d9-4cd4-82e7-0a7c77c3d0be.png">

**Comment by tisfeng** [comment]
我提交了一个版本更新 PR，包括优化语种识别速度 https://github.com/raycast/extensions/pull/5424
