### ISSUE TITLE
可以结合 PopClip 实现更好的使用体验

### ISSUE THREAD

**Issue by Apolsus** [tisfeng/Raycast-Easydict#30]
## 功能描述

结合 popclip 可以实现更高效的划词，所幸实现这一功能不需要太多努力

## 使用场景（可选）

![CleanShot 2023-01-23 at 12 11 49](https://user-images.githubusercontent.com/59809602/213964649-be119154-4e98-4418-ad5d-fde5b24b3e57.gif)

## 实现方法

1. 安装 PopClip
2. 仿照 Saladict 创建一个插件，其中 apple script 部分设置好触发快捷键
3. 设置 Raycast 当中 EasyDict 的快捷键，应当与 PopClip 插件一致。

**Comment by tisfeng** [comment]
你好，新年快乐～

如果你是想说通过 PopClip 调用 Easydict 的话，目前这个是支持的 https://github.com/tisfeng/Raycast-Easydict#use-with-popclip
