### ISSUE TITLE
【功能建议】接入 OpenAI API

### ISSUE THREAD

**Issue by six-ddc** [tisfeng/Raycast-Easydict#32]
请问有考虑通过接入 openai gpt API 来增强翻译能力吗？实测 gpt 的翻译是要比 DeepL 好用的。

**Comment by tisfeng** [comment]
可以，有段时间没写 TS 了，有小伙伴来 PR 吗 🤓

**Comment by six-ddc** [comment]
> 可以，有段时间没写 TS 了，有小伙伴来 PR 吗 🤓

会一点 ts，我有空尝试一下 😁

**Comment by tisfeng** [comment]
可以，欢迎 PR 🤗

**Comment by tisfeng** [comment]
有小伙伴想写这个功能吗？没有的话我就抽空自己写一下了 😔

**Comment by tisfeng** [comment]
已提交 PR 支持了 OpenAI 翻译 https://github.com/raycast/extensions/pull/5424

**Comment by tisfeng** [comment]
请问具体是如何报错的？是进去就报错，还是超时崩溃，可以录个视频我看一下吗

**Comment by tisfeng** [comment]
OpenAI 请求时，默认会读取系统代理，如果没有代理，或者代理 IP 不符合 OpenAI 的判定，可能会报错 😢

**Comment by tisfeng** [comment]
修复优化了一下，你用仓库最新的代码跑一下看看 😤

**Comment by tisfeng** [comment]
商店 PR 也已经合并了 https://github.com/raycast/extensions/pull/5615 ，请测试一下。

**Comment by six-ddc** [comment]
好了，现在不会崩溃啦
