### ISSUE TITLE
🐞 反馈问题：OpenAI Translate Error While OpenAI Translate is disabled

### ISSUE THREAD

**Issue by zhenpewu** [tisfeng/Raycast-Easydict#36]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

The error notification pop up while OpenAI Translate is disabled, the error message the API token is not provided.
<img width="886" alt="Screen Shot 2023-03-28 at 13 53 05" src="https://user-images.githubusercontent.com/96321255/228366748-cbf7116b-7510-4b39-85a0-9891f0ae0f0d.png">

![Screen Shot 2023-03-28 at 13 56 01](https://user-images.githubusercontent.com/96321255/228366753-39a277c1-7ffa-420a-8d58-28e365133f3b.png)

### 重现步骤

N/A

### 期望结果

If any service is disabled, the related error message should not pop up.

**Comment by zhenpewu** [comment]
I believe it is due to this line https://github.com/tisfeng/Raycast-Easydict/blob/74665f7b384fe0f547eb91f05bcec44e2a873216/src/dataManager/dataManager.ts#L745

```
    // if (myPreferences.enableOpenAITranslate)

```

**Comment by tisfeng** [comment]
Thank you for your feedback. You are right. Initially, I commented out the code when testing it and forgot to uncomment it later.

**Comment by zhenpewu** [comment]
I have raised one PR https://github.com/tisfeng/Raycast-Easydict/pull/37, feel free to merge it.
