### ISSUE TITLE
🚀 功能建议：调用本地Eudic查词

### ISSUE THREAD

**Issue by imshenshen** [tisfeng/Raycast-Easydict#38]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过，未发现类似功能建议
- [X] Easydict 已升级到最新版本

### 功能描述

建议添加本地欧路词典查词，而不是查询结果后，再通过更多命令打开Eudic。
不知道这个好实现么？

**Comment by tisfeng** [comment]
之前我尝试过，但这个不太好弄，首先 Eudic 官方不提供对外 API，即使网页版 https://dict.eudic.net/dicts/en/good 抓包一看，返回的数据居然是 HTML，我吐了，实在不想去手写解析，太累了。

如果小伙伴有好的解决方法，可以告知一下。 如果不怕苦不怕累，手动爬虫也行，PR 欢迎你，虽然实现不优雅，但又不是不能用 🫠
