### ISSUE TITLE
🐞 反馈问题：openAI translation is missing the first word

### ISSUE THREAD

**Issue by aieai** [tisfeng/Raycast-Easydict#39]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

<img width="1000" alt="easydict 2023-04-25 at 18 53 27" src="https://user-images.githubusercontent.com/11988373/234255871-69ddf42a-94b1-47bb-ad8a-d9cbf2d72744.png">
<img width="1000" alt="easydict 2023-04-25 at 18 52 44" src="https://user-images.githubusercontent.com/11988373/234255899-0fbbf9e5-360e-486a-9cf3-d58b38cd8607.png">

### 重现步骤

use free personal api

### 期望结果

修复

**Comment by aieai** [comment]
then “use system proxy” invalid

**Comment by tisfeng** [comment]
Thanks for the feedback, I checked and the two issues you mentioned do exist, I will release a new fix to the store later.

I've fixed them on the latest code in this repository, you can try it first.

**Comment by tisfeng** [comment]
A new version has been released, please update it.

**Comment by aieai** [comment]
thanks for u speed, I really like this plugin, it's nice, then expect easydict1.2.4

**Comment by tisfeng** [comment]
Thanks for your loving~

Easydict will release a new version this week.

**Comment by aieai** [comment]
use system proxy still not working

**Comment by tisfeng** [comment]
New version 1.3.0  https://github.com/tisfeng/Easydict/releases/tag/1.3.0

**Comment by aieai** [comment]
Bravo
