### ISSUE TITLE
🚀 功能建议：增加朗读快捷键功能，希望快捷键可定制

### ISSUE THREAD

**Issue by Wu-XiaoLin** [tisfeng/Raycast-Easydict#42]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过，未发现类似功能建议
- [x] Easydict 已升级到最新版本

### 功能描述

希望为 raycast 插件增加朗读快捷键功能（原文和结果希望都能朗读），且希望快捷键可定制

**Comment by tisfeng** [comment]
目前只能朗读查询文本。由于查询结果可能有多个，这个朗读不好处理。快捷键可定制，可以做，但太麻烦，如果有 PR 就好了。
