### ISSUE TITLE
🐞 反馈问题：新版本不能正常使用

### ISSUE THREAD

**Issue by zhenpewu** [tisfeng/Raycast-Easydict#43]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

1. query specified in argument 不会传进 command 内
2. 一直在加载，不加载 result

### 重现步骤

N/A

### 期望结果

N/A

**Comment by tisfeng** [comment]
我这边测试没有问题，而且新版本只是加了一个 OCR 截图翻译的新动作，应该不会对其他功能造成影响的。

可能语种识别出现了问题，你看一下是不是和这个问题一样 https://github.com/raycast/extensions/issues/6699#issuecomment-1557366925 ，请尽量开启两个以上的语种识别服务，至少保证有一个能正常使用。

**Comment by zhenpewu** [comment]
好像可以用了就是非常慢，之前没有这么慢。
然后 query 确实还是不传进去。

**Comment by zhenpewu** [comment]
<img width="886" alt="Screenshot 2023-05-26 at 21 51 37" src="https://github.com/tisfeng/Raycast-Easydict/assets/96321255/ce7b43a8-6743-425a-b922-ec8593e1b978">
<img width="1112" alt="Screenshot 2023-05-26 at 21 51 35" src="https://github.com/tisfeng/Raycast-Easydict/assets/96321255/9f119f98-f2ac-48a7-9681-98f9b616cc68">

**Comment by tisfeng** [comment]
看一下你的设置，是不是把这个关闭了？关闭这个，意味着你至少需要开启两个语种识别服务，否则就会出现异常。

<img width="1036" alt="image" src="https://github.com/tisfeng/Raycast-Easydict/assets/25194972/72d6b933-3f2a-435a-89ce-d54cab520005">

**Comment by nzhl** [comment]
这个问题我也有, 就是有时候翻译加载不出来, 不是新版, 之前的版本也存在

**Comment by tisfeng** [comment]
前面说了，这种情况大概率是语种识别卡住了，目前默认只启用了 Bing 语种识别，但这个接口也不稳定，因此最好配合其他语种识别服务一起用。

考虑到隐私问题，其他语种识别服务（百度，腾讯和火山）只在用户开启相应的翻译服务时才启用，建议至少开启其中一个，且要确保这个服务接口查询正常。

之前百度，腾讯和火山翻译都是使用我私人的 App Key，所以不会有问题，但后面用户多了，免费额度不够用，我还收到过超支账单，只好停了内置的百度和火山 😓 。如果要用，请配置自己的 Key。

**Comment by tisfeng** [comment]
这个项目当初只是我一时兴起做的，现在精力主要在另一个项目 [Easydict](https://github.com/tisfeng/easydict)

**Comment by zhenpewu** [comment]
我 “Detect Language Speed First" 是 checked 的。我之前也是没有用 百度/腾讯/火山，我有选择三个 google, linguee 和 apple。

**Comment by zhenpewu** [comment]
```
9:38:34.362 start requestWebBingTranslate
09:38:34.650 get bing config cost time: 776
09:38:34.653 start requestWebBingTranslate
09:38:34.789 bing translate cost time: 434
09:38:34.789 bing translate response is empty, tld: cn, check ip again, then request again
09:38:34.790 check if ip in China
09:38:34.890 bing translate cost time: 242
09:38:34.890 bing translate response is empty, tld: cn, check ip again, then request again
09:38:34.890 check if ip in China
09:38:35.171 getCurrentIp error: AxiosError: Request failed with status code 429
09:38:35.171 checkIfIpInChina error: AxiosError: Request failed with status code 429
09:38:35.171 get bing tld: cn
09:38:35.172 bing tld is changed to: cn, try request token and bing translate again
09:38:35.172 start requestBingConfig
09:38:35.172 config bingTld: cn
09:38:35.172 get bing config url: https://cn.bing.com/translator
09:38:35.265 getCurrentIp error: AxiosError: Request failed with status code 429
09:38:35.265 checkIfIpInChina error: AxiosError: Request failed with status code 429
09:38:35.265 get bing tld: cn
09:38:35.266 bing tld is changed to: cn, try request token and bing translate again
09:38:35.266 start requestBingConfig
09:38:35.266 config bingTld: cn
09:38:35.266 get bing config url: https://cn.bing.com/translator
09:38:35.697 get bing config cost time: 522
09:38:35.700 start requestWebBingTranslate
09:38:35.775 get bing config cost time: 506
09:38:35.780 start requestWebBingTranslate
09:38:35.946 bing translate cost time: 252
09:38:35.946 bing translate response is empty, tld: cn, check ip again, then request again
09:38:35.946 check if ip in China
09:38:36.216 bing translate cost time: 445
09:38:36.216 bing translate response is empty, tld: cn, check ip again, then request again
09:38:36.216 check if ip in China
09:38:36.301 getCurrentIp error: AxiosError: Request failed with status code 429
09:38:36.301 checkIfIpInChina error: AxiosError: Request failed with status code 429
09:38:36.301 get bing tld: cn
09:38:36.302 bing tld is changed to: cn, try request token and bing translate again
09:38:36.302 start requestBingConfig
09:38:36.302 config bingTld: cn
09:38:36.302 get bing config url: https://cn.bing.com/translator
```

我clone了这个 repo 到我本地，这是我看到的 log, 对于我的 case 可能是 bing 有点问题，你假如是 什么 insights 可以告诉我一下，我有空也可以自己看一下。

**Comment by woyin** [comment]
看来我不是一个人，这个插件的确是非常慢，我也有遇到相同的问题。

**Comment by tisfeng** [comment]
@zhenpewu Bing 语种识别不稳定，因为这个野生接口分中国特供版和国际版，不能混用，必须先判断用户 IP，不然会失败，很麻烦。

如果你有兴趣，可以优化一下语种识别过程，将语种识别配置独立出来，而不是和翻译服务混在一起，因为有些用户可能只开启部分翻译服务，如果里面不包括语种识别 API，就会导致卡住，速度慢等问题。

目前支持的语种识别服务： Bing，百度，腾讯和火山，Google 也支持，但因为之前中国版 Google 翻译被墙了，就没有使用，你可以把它加上，分别为它们弄个开关设置，默认启用几个，如 Bing，百度。

期待你的 PR。

**Comment by zhenpewu** [comment]
嗯嗯，我现在只是把它改到了 我自己能用的状态 😀，我有空看看 我有什么地方可以优化的。

**Comment by so2liu** [comment]
如果有朋友遇到了相同的问题，大概率是翻墙了。我本地泡了一下项目，没理解在没有配置raycast proxy的情况下还会使用例如http://127.0.0.1:7890作为proxy。可以把proxy改成直联试一下。

之后我打算改进一下这个问题，另外想办法做成本地优先的
