### ISSUE TITLE
🐞 反馈问题：不能自动 query 选中文本

### ISSUE THREAD

**Issue by Unrealluver** [tisfeng/Raycast-Easydict#45]
### 请先确认以下事项

- [X] 已仔细阅读了 [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] 在 [issues](https://github.com/tisfeng/Raycast-Easydict/issues) 页面搜索过问题，但未能找到解决方法
- [X] Easydict 已升级到最新版本

### 问题描述

raycast 已经更新到最新版本，同时 easydict plugin 也是应用商店内最新的版本。

设置如图：
![image](https://github.com/tisfeng/Raycast-Easydict/assets/27504120/7f47340b-4709-4b2c-9120-b5e7020f1f6c)

### 重现步骤

在选中文本并敲击 快捷键时，并不会自动 query 选中文本：
<img width="914" alt="image" src="https://github.com/tisfeng/Raycast-Easydict/assets/27504120/649069c7-429c-4626-9b7e-d76e397e28c5">

求作者大大支支招。

### 期望结果

希望能够自动 query 选中文本。

**Comment by tisfeng** [comment]
有时候取词确实可能会失败，极小概率，但这个是 Raycast API 问题，也没什么办法，一般来说正常取词是会成功的。

<img width="1338" alt="image" src="https://github.com/tisfeng/Raycast-Easydict/assets/25194972/a5437ed7-3372-4c03-8a6a-4b8458003487">

**Comment by bravelincy** [comment]
我也遇到这个问题了，选中的文字不能自动输入的问题发生的概率还是蛮高的。

**Comment by friendwu** [comment]
1. go to Macos System Preferences --> security & privacy --> Accessibility
2. enable Raycast
3. retry

this solution works for me.

**Comment by sagiwei** [comment]
> 1. go to Macos System Preferences --> security & privacy --> Accessibility
> 2. enable Raycast
> 3. retry
> 
> this solution works for me.

Not work for me 😭

**Comment by soulofshadow** [comment]
<img width="1136" alt="image" src="https://github.com/tisfeng/Raycast-Easydict/assets/95683271/c22beb62-ae25-4988-82e8-240ee7ff83a3">
有人和我一样吗，Translation services 我全开才能正常翻译，如果我只保留我需要的几个，就会一直翻译不出来。。

**Comment by tisfeng** [comment]
参考这个 https://github.com/tisfeng/Raycast-Easydict/issues/43#issuecomment-1566129559

**Comment by tisfeng** [comment]
行吧，稍后我优化一下，默认多启用几个语种识别服务。
