### ISSUE TITLE
支持 getSelectedText

### ISSUE THREAD

**Issue by yufeikang** [tisfeng/Raycast-Easydict#5]
Hello。很棒的ext。感谢您的贡献。

是否有空支持一下 getSelectedText。
https://developers.raycast.com/api-reference/environment#getselectedtext

我感觉会很方便，不用占用剪切板历史list。或者我可以给你提pr吗

**Comment by yufeikang** [comment]
抱歉，看到已经支持了。棒

**Comment by tisfeng** [comment]
额，是的，我一开始没发现这个 API，现在已经改用 `getSelectedText` 了 8ad56f5336ec86f5d87b8020976f81530fd40ffa ，只是目前还没有发布新版本，我在整理代码，这两天会发布一个新的版本。 感谢反馈
