### ISSUE TITLE
🐞 Bug Report: Please fill in the title, don't leave it blank

### ISSUE THREAD

**Issue by stake-zh** [tisfeng/Raycast-Easydict#59]
### Please confirm the following:

- [X] I have carefully read the [README](https://github.com/tisfeng/Raycast-Easydict#readme)
- [X] I have searched through the [issues](https://github.com/tisfeng/Raycast-Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [X] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Raycast-Easydict/releases)
- [X] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

苹果本地词典不生效，已经安装shortcuts，提示“Get Dictionary Value failed because Shortcuts couldn’t convert from Text to Dictionary.”

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

勾选了苹果翻译

### Screenshot

<img width="309" alt="image" src="https://github.com/tisfeng/Raycast-Easydict/assets/3991352/d2dfa27f-cdf9-44f3-89e9-a5582e2dbcfc">

### Expected result

可以生效

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR

**Comment by tisfeng** [comment]
你的问题很奇怪，这个项目不支持苹果词典，请准确、清晰、详细地描述你的问题。

截图也不完整，不要吝啬，如果不涉及隐私，请提供全屏完整的截图。如果截图不能表达你的问题，请提供录屏。
