### ISSUE TITLE
Automatic query clipboard is not working.

### ISSUE THREAD

**Issue by liCells** [tisfeng/Raycast-Easydict#6]
I unchecked automatic query clipboard checkbox, but it didn't work.

About:

- MacBook air m1
- System version Monterey 12.4
- Raycast version 1.36.1

**Comment by tisfeng** [comment]
Hi  @liCells  Thank you for your feedback.

This is a known problem, and I have submitted a new version [PR](https://github.com/raycast/extensions/pull/2040)  in the store , replacing query clipboard with selected text. Or you can use the latest version of the current repository directly.

**Comment by liCells** [comment]
There is something wrong with my description.
This is how I understand this function: it is used to automatically query the content of the clipboard, so if unchecked, should the clipboard content not be automatically filled?

The current situation is that I have unchecked it, but it will still be automatically queried.

My English is relatively poor, hope to understand.

---

我认为这个功能是用来自动查询剪切板内容的, 我取消了勾选, 但是在进入插件后依然会自动进行查询.

**Comment by tisfeng** [comment]
> 我取消了勾选, 但是在进入插件后依然会自动进行查询

额，是的，你反馈的这个问题确实存在，之前由于代码 bug 导致取消剪贴板查询无效 😂

当前仓库最新版本，已改用 [划词搜索](https://developers.raycast.com/api-reference/environment#getselectedtext) 替代剪贴板查询。 另外，我也向扩展商店提交了一个新版本 [PR](https://github.com/raycast/extensions/pull/2040) ，正等待审核。

**Comment by liCells** [comment]
哈哈, 好的.😁
